[package]
name = "riot-api"
version = "0.1.0"
edition = "2021"

[lib]
name = "riot_api"
path = "src/lib.rs"

[dependencies]
actix-web = "4.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
base64 = "0.21"
hmac = "0.12"
sha2 = "0.10"
env_logger = "0.10"
log = "0.4"
